apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-http
  name: hello-http
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 32000
  selector:
    app: hello-http
  type: NodePort
status:
  loadBalancer: {}
