apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-http
  name: hello-http
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: helloport
  selector:
    app: hello-http
status:
  loadBalancer: {}
