apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-http
  name: hello-http
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-http
  template:
    metadata:
      labels:
        app: hello-http
    spec:
      containers:
      - image: bob2606/hello-http:0.8.29
        name: hello-http
        ports:
          - name: helloport
            containerPort: 88
        envFrom:
          - configMapRef:
              name: hello-http
          - secretRef:
              name: hello-http
