apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: www
    env: dev
  name: www
spec:
  replicas: 3
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      initContainers:
      - image: busybox:1.28
        name: init-1
        volumeMounts:
          - name: init
            mountPath: /data
        command:
          - sh
          - -c
          - date > /data/date.txt
      containers:
      - image: nginx:1.28
        name: nginx
        volumeMounts:
          - name: init
            mountPath: /mnt
        env:
          - name: STAGE
            value: Kubernetes
          - name: JOURS
            value: "5"
          - name: PODIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: INTERVENTION
            valueFrom:
              configMapKeyRef:
                name: www
                key: FORMATION
        envFrom:
          - configMapRef:
              name: www
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 5
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 10
          failureThreshold: 2

      volumes:
        - name: init
          emptyDir:
            medium: Memory
