apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: www
    env: dev
  name: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        env:
          - name: STAGE
            value: Kubernetes
          - name: JOURS
            value: "5"
          - name: PODIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: INTERVENTION
            valueFrom:
              configMapKeyRef:
                name: www
                key: FORMATION
